//
// Created by Fedchenko Yaroslav on 21.11.2019.
//

#ifndef SVECTOR_FEDCHENKO_YAROSLAV_DMATRIX_TESTS_H
#define SVECTOR_FEDCHENKO_YAROSLAV_DMATRIX_TESTS_H
void type_test();
#endif //SVECTOR_FEDCHENKO_YAROSLAV_DMATRIX_TESTS_H
